<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sakshi" failures="0" tests="3" name="coverFoxTest.CoverFoxTC1" time="2.647" errors="1" timestamp="2024-08-09T20:51:25 IST" skipped="2">
  <testcase classname="coverFoxTest.CoverFoxTC1" name="validateBanners" time="0.000">
    <skipped/>
    <system-out>
      <![CDATA[nullTC execution started]]>
    </system-out>
  </testcase> <!-- validateBanners -->
  <testcase classname="coverFoxTest.CoverFoxTC1" name="preConditions" time="2.647">
    <error message="&quot;C:\Users\saksh\OneDrive\Documents\sakshiExceldoc (1).xlsx (The filename, directory name, or volume label syntax is incorrect)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: "C:\Users\saksh\OneDrive\Documents\sakshiExceldoc (1).xlsx (The filename, directory name, or volume label syntax is incorrect)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
at coverFoxUtility.Utility.readDataFromExcel(Utility.java:34)
at coverFoxTest.CoverFoxTC1.preConditions(CoverFoxTC1.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
    <system-out>
      <![CDATA[click on male button
clickOnnextButton]]>
    </system-out>
  </testcase> <!-- preConditions -->
  <testcase classname="coverFoxTest.CoverFoxTC1" name="validatePresenceOfSortButton" time="0.000">
    <skipped/>
  </testcase> <!-- validatePresenceOfSortButton -->
  <system-out>
    <![CDATA[lauching browser
waiting...
lauching browser
waiting...
click on male button
clickOnnextButton
nullTC execution started
nullTC execution started
nullTC execution started
nullTC execution started]]>
  </system-out>
</testsuite> <!-- coverFoxTest.CoverFoxTC1 -->
